In [1]:
import numpy as np

In [3]:
np.arange(start=2, stop=50, step=3)

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47])

In [15]:
import numpy as np

In [16]:
list1 = []
for i in range(0,5):
    element = int(input())
    
    list1.append(element)
    
print("List 1 is:- ",list1)

nplist1 = np.array(list1)
print("Array 1 is:- ",nplist1)
    
list2 = []
for i in range(0,5):
    element = int(input())
    
    list2.append(element)
    
print("List 2 is:- ",list2)
nplist2 = np.array(list2)
print("Array 2 is:- ",nplist2)

21
34
1
56
98
List 1 is:-  [21, 34, 1, 56, 98]
Array 1 is:-  [21 34  1 56 98]
45
26
87
15
69
List 2 is:-  [45, 26, 87, 15, 69]
Array 2 is:-  [45 26 87 15 69]


In [17]:
con_arr = np.concatenate((nplist1,nplist2))
print(con_arr)

[21 34  1 56 98 45 26 87 15 69]


In [18]:
sort_arr = np.sort(con_arr)
print(sort_arr)

[ 1 15 21 26 34 45 56 69 87 98]


In [19]:
import numpy as np
 
arr = np.array( [[ 1, 2, 3],
                 [ 4, 2, 5]] )
 
print("Array is of type: ", type(arr))
 
print("No. of dimensions: ", arr.ndim)
 
print("Shape of array: ", arr.shape)
 
print("Size of array: ", arr.size)
 
print("Array stores elements of type: ", arr.dtype)

Array is of type:  <class 'numpy.ndarray'>
No. of dimensions:  2
Shape of array:  (2, 3)
Size of array:  6
Array stores elements of type:  int32


In [20]:
import numpy as np
array = np.arange(8) 
print("Original array : \n", array)
array = np.arange(8).reshape(2, 4)
print("New array : \n", array)

Original array : 
 [0 1 2 3 4 5 6 7]
New array : 
 [[0 1 2 3]
 [4 5 6 7]]


In [21]:
import numpy as np
f = np.array([1,2,3])
g = np.array([4,5,6])

print('Horizontal Append:', np.hstack((f, g)))


print('Vertical Append:', np.vstack((f, g)))

Horizontal Append: [1 2 3 4 5 6]
Vertical Append: [[1 2 3]
 [4 5 6]]


In [28]:
import numpy as np
arr = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18,55,45,55,45])
print('Original Numpy Array : ' , arr)

unique_elements, counts_elements = np.unique(arr, return_counts=True)
print("Frequency of unique values of the said array:")
print(np.asarray((unique_elements, counts_elements)))


Original Numpy Array :  [11 11 12 13 14 15 16 17 12 13 11 14 18 55 45 55 45]
Frequency of unique values of the said array:
[[11 12 13 14 15 16 17 18 45 55]
 [ 3  2  2  2  1  1  1  1  2  2]]
